version: '3'

services:
  node:
    image: hyperledger/iroha:1.2.1
    container_name: iroha_node_1
    ports:
      - "50051:50051"
    environment:
      - IROHA_HOME=/opt/iroha
      - IROHA_CONF=config.docker
      - IROHA_NODEKEY=node1
      - CCACHE_DIR=/tmp/ccache
    volumes:
      - ${PWD}/example:/opt/iroha/config
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha/config
    entrypoint: /opt/iroha/config/entrypoint.sh
    depends_on:
      - postgres

  postgres:
    image: postgres:13.2-alpine
    container_name: iroha_postgres_1
    environment:
      - POSTGRES_USER=iroha
      - POSTGRES_PASSWORD=HelloW0rld

volumes:
  ccache-data:
